### ISSUE TITLE
Why did the server crash?

### ISSUE THREAD

**Issue by dphiffer** [dphiffer/firewall-cafe#12]
Here is the stack trace:

```
Images: undefined
Images: undefined
events.js:141
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected token u
    at Object.parse (native)
    at /home/dphiffer/firewall-cafe/server/index.js:265:34
    at /home/dphiffer/firewall-cafe/server/node_modules/google-spreadsheet/index.js:148:15
    at Parser.<anonymous> (/home/dphiffer/firewall-cafe/server/node_modules/google-spreadsheet/node_modules/xml2js/lib/xml2js.js:484:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (/home/dphiffer/firewall-cafe/server/node_modules/google-spreadsheet/node_modules/xml2js/lib/xml2js.js:445:26)
    at emit (/home/dphiffer/firewall-cafe/server/node_modules/google-spreadsheet/node_modules/xml2js/node_modules/sax/lib/sax.js:639:35)
    at emitNode (/home/dphiffer/firewall-cafe/server/node_modules/google-spreadsheet/node_modules/xml2js/node_modules/sax/lib/sax.js:644:5)
    at closeTag (/home/dphiffer/firewall-cafe/server/node_modules/google-spreadsheet/node_modules/xml2js/node_modules/sax/lib/sax.js:903:7)
```

**Comment by dphiffer** [comment]
Also this:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected token u
    at Object.parse (native)
    at /home/dphiffer/firewall-cafe/server/index.js:266:33
    at /home/dphiffer/firewall-cafe/server/node_modules/google-spreadsheet/index.js:148:15
    at Parser.<anonymous> (/home/dphiffer/firewall-cafe/server/node_modules/google-spreadsheet/node_modules/xml2js/lib/xml2js.js:484:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (/home/dphiffer/firewall-cafe/server/node_modules/google-spreadsheet/node_modules/xml2js/lib/xml2js.js:445:26)
    at emit (/home/dphiffer/firewall-cafe/server/node_modules/google-spreadsheet/node_modules/xml2js/node_modules/sax/lib/sax.js:639:35)
    at emitNode (/home/dphiffer/firewall-cafe/server/node_modules/google-spreadsheet/node_modules/xml2js/node_modules/sax/lib/sax.js:644:5)
    at closeTag (/home/dphiffer/firewall-cafe/server/node_modules/google-spreadsheet/node_modules/xml2js/node_modules/sax/lib/sax.js:903:7)
```

**Comment by dphiffer** [comment]
Needed a `try` / `catch` around the JSON parsing.
